FROM ubuntu:22.04

ARG ARCH=arm64
ARG VERSION=1.19.4

ENV ARCH=${ARCH}
ENV VERSION=${VERSION}

RUN apt-get update && apt install iproute2 make libc6 curl openssh-server sudo git net-tools iputils-ping lsb-release -y


# nodeJS installation

RUN mkdir /usr/local/nvm
ENV NVM_DIR /usr/local/nvm
ENV NVM_VERSION=v0.39.3
ENV NODE_VERSION 18.13.0
RUN curl https://raw.githubusercontent.com/nvm-sh/nvm/${NVM_VERSION}/install.sh | bash \
    && . $NVM_DIR/nvm.sh \
    && nvm install $NODE_VERSION \
    && nvm alias default $NODE_VERSION \
    && nvm use default

ENV NODE_PATH $NVM_DIR/v$NODE_VERSION/lib/node_modules
ENV PATH $NVM_DIR/versions/node/v$NODE_VERSION/bin:$PATH

# RUN echo "[[ -s $NVM_DIR/nvm.sh ]] && . $NVM_DIR/nvm.sh" >> $HOME/.bashrc;

# nodeJS installation

RUN systemctl enable ssh

EXPOSE 22

CMD ["/sbin/init", "&&", "service ssh start"]